[package]
name = "actix_grpc_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
prost = "0.13.3"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.12.3", features = ["transport"] }

[build-dependencies]
tonic-build = "0.12.3"
